stages:
  # Liste des etapes ( correspond au tags des des runners)
  - test
  - dev-deployement


test:
  stage: test

  before_script:
    - pip install --upgrade pip
    - pip install flask
    - pip install bs4

  script:
    # Lancement des tests unitaires
    - python -m unittest tests.test_pages
    #- python -m unittest tests.test_enigme2

  image: python:3.6


dev-deployement:
  stage: dev-deployement

  script:
    - apt update
    - apt install -y lftp
    - lftp -f "open fifoandlifo.fr  user dev cpo\$094y%  lcd ./ mirror --reverse --delete --verbose  --parallel=4  ./ / bye"

  image: amd64/ubuntu:latest
