image: python:3.6

stages:
  # Liste des etapes ( correspond au tags des des runners)
  - test

test:
  stage: test

  before_script:
    - pip install --upgrade pip
    - pip install flask
    - pip install bs4

  script:
    # Lancement des tests unitaires
    - python -m unittest tests.test_basic
    #- python -m unittest tests.test_enigme2