image: amd64/ubuntu:latest

stages:
  # Liste des etapes ( correspond au tags des des runners)
  - test
  - dev-deployement

test:
  stage: test

  before_script:
    - apt-get update
    - apt install -y lftp
    - apt install -y python3-pip
    - pip3 install --upgrade pip
    - pip3 install flask
    - pip3 install bs4

  script:
    # Lancement des tests unitaires
    - python3 -m unittest tests.test_pages
    #- python -m unittest tests.test_enigme2


dev-deployement:
  stage: dev-deployement

  script:
    - lftp -f "open fifoandlifo.fr  user dev cpo$094y%  lcd ./ mirror --reverse --delete --verbose  --parallel=4  ./ / bye"