stages:
  # Liste des etapes ( correspond au tags des des runners)
  - test
  - dev-deployement


test:
  stage: test

  before_script:
    - pip install --upgrade pip
    - pip install flask
    - pip install bs4

  script:
    # Lancement des tests unitaires
    - python -m unittest tests.test_pages
    #- python -m unittest tests.test_enigme2

  image: python:3.6


dev-deployement:
  stage: dev-deployement

  script:
    - apt update
    - apt install -y lftp

    - ls 
    - lftp ftp://dev:cpo\$094y%@fifoandlifo.fr  -e "-mirror ./ ./"


  image: amd64/ubuntu:latest
